# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServiceBusTui < Formula
  desc "A terminal-based explorer for Azure Service Bus"
  homepage "https://github.com/MonsieurTib/service-bus-tui"
  version "1.0.1-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MonsieurTib/service-bus-tui/releases/download/v1.0.1-alpha/service-bus-tui_Darwin_x86_64.tar.gz"
      sha256 "1924fffd94f4cbf498029498a300d84e95228049acb70f1f976710a803aacdf7"

      def install
        bin.install "service-bus-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MonsieurTib/service-bus-tui/releases/download/v1.0.1-alpha/service-bus-tui_Darwin_arm64.tar.gz"
      sha256 "3f0ea727e9d761a58f491b2462564896c27d4bf863ed31a2e1787c8542386072"

      def install
        bin.install "service-bus-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MonsieurTib/service-bus-tui/releases/download/v1.0.1-alpha/service-bus-tui_Linux_x86_64.tar.gz"
      sha256 "a4b4f301be07a3a0554bcb4916c7ef44143d9fea52c49d7f61a354a1eb1955d0"
      def install
        bin.install "service-bus-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MonsieurTib/service-bus-tui/releases/download/v1.0.1-alpha/service-bus-tui_Linux_arm64.tar.gz"
      sha256 "218bbd39c674e262fed6d9680ddaf53e47e19ec7e78180b4306d11cb96f8a161"
      def install
        bin.install "service-bus-tui"
      end
    end
  end

  test do
    system "#{bin}/service-bus-tui", "--version"
  end
end
